vich_uploader:
  db_driver: orm
  metadata: { type: attribute }
  mappings:
    order_asset:
      uri_prefix: /uploads/order-assets
      upload_destination: '%kernel.project_dir%/public/uploads/order-assets'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    order_thumbnail:
      uri_prefix: /uploads/order-thumbnails
      upload_destination: '%kernel.project_dir%/public/uploads/order-thumbnails'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer